### ISSUE TITLE
Facing the error not found page after canceling the payment

### ISSUE THREAD

**Issue by mfarim** [shabrina12/FullStack-Ecommerce-Clothing-Web#3]
## Description
Page not found after canceling the payment on the checkout page.
Link: https://full-stack-ecommerce-clothing-web.vercel.app

## How to reproduce
1. Add products to the cart
<img width="1557" alt="image" src="https://github.com/shabrina12/FullStack-Ecommerce-Clothing-Web/assets/7545546/ea0c5565-5a82-4785-9168-d5d3055d2595">

2. Click the button Process to checkout
<img width="1545" alt="image" src="https://github.com/shabrina12/FullStack-Ecommerce-Clothing-Web/assets/7545546/56b0eb42-85f6-46e8-93ad-13aa9991561b">

3. Click the button back on the payment page (Test mode)
<img width="1282" alt="image" src="https://github.com/shabrina12/FullStack-Ecommerce-Clothing-Web/assets/7545546/fb81607c-1efa-4b04-8f84-5e5f2b5d4b24">

4. The 404 page appears
<img width="1454" alt="image" src="https://github.com/shabrina12/FullStack-Ecommerce-Clothing-Web/assets/7545546/861dbfd7-1aaa-42cf-ad2a-36194b73ca79">

5. Expected no error appears.

**Comment by shabrina12** [comment]
Hi @MuhammadFariMadyan, I seem to have forgotten to create a cancel page, so a quick solution for now is that when the user click the back button, the page will redirect to the cart page (note that the cart will be empty). I've already pushed the latest changes. Thank you for your comment
